CONTRIBUTING.md
CONTRIBUTION.md

documentation:add CONTRIBUTION.md

---

LOGISTICAL.csv

提供目前可查到官方声明的免费物流信息，其中菜鸟属联合物流支持，应为首选
Signed-off-by: Frankzhaopku <syzhao1988@126.com>

logistical: add logistical info, #3

---

.github/hypertrons.json

Signed-off-by: WuShaoling <wsl6@outlook.com>

refactor: add approver

---

LOGISTICAL.csv

圆通速递有限公司，武汉寄入，不接受个人捐助；中通快递集团，武汉寄入，不接受个人捐助

---

README.md

添加石墨文档地址
Signed-off-by: Frankzhaopku <syzhao1988@126.com>

refactor: add doc

---

CONTRIBUTION.md

* 更清晰的指南。
* 移除 CSV 指南文档。
Signed-off-by: LinHaiming <lhming23@outlook.com>

doc:update CONTRIBUTING #1

---

README.md

doc:update README.md

---

README.md

修正README.ME中的贡献指南链接

---

README.md

Signed-off-by: Frankzhaopku <syzhao1988@126.com>

fix: readme slack link

---

README.md

[bug]Fix README bug

---

INFORMATION_GUIDE.md
README.md

add information of the new table, Travel_Hotel

doc:update INFORMATION_GUIDE & README

---

FAQ_EN.md
README_EN.md

* added `FAQ_EN.md`, author: Lili, proofreader: @JoeZijunZhou
* updated `README_EN.md`, author: @CNYoki , proofreader: @Atena1118 @JoeZijunZhou

doc: FAQ English version & README update

---

README.md
README_EN.md

~Do NOT merge yet, the markdown table seems to be broken...~
Please take a look at the PR, thanks!

Add Slack Navigations and Improve the wording of the English version of readme

---

README.md

* add badge link to https://wuhan2020.github.io/

doc: add badge for official announcement

---

FAQ.md
FAQ_EN.md
README.md
README_EN.md

Fix #263. #176
Update:
1. Validate invitation link in `FAQ.md`
2. Guide user from `FAQ.md` to the detailed channel section in `README.md`

Update FAQ Slack link

---

README.md
WUHAN2020_OFFICIAL_ANNOUNCEMENT.md

add official announcement EN

---

README.md

fix badge link

---

CONTRIBUTING.md
CONTRIBUTING_EN.md
FAQ.md
FAQ_EN.md
README_EN.md

chore: fix slack invite links

---

WUHAN2020_OFFICIAL_ANNOUNCEMENT.md
WUHAN2020_OFFICIAL_ANNOUNCEMENT_EN.md

official announcement format

---

WUHAN2020_OFFICIAL_ANNOUNCEMENT_EN.md

* fix official announcement redirect link

doc: fix readme link

---

WUHAN2020_OFFICIAL_ANNOUNCEMENT.md
WUHAN2020_OFFICIAL_ANNOUNCEMENT_EN.md
WUHAN2020_OFFICIAL_ANNOUNCEMENT_FR.md

* French Official Announcement

doc: add french OA

---

LICENSE

LICENSE got deleted in #304 
Re-introduce in this PR.
Relates to #296

Re add LICENSE

---

README_JP.md

Update translation readme jp

---

README_TW.md

Create Traditional Chinese Readme

Create Traditional Chinese Readme

---

README.md
README_EN.md
README_IT.md
README_JP.md
README_TW.md

Add TW README to the other READMEs

---

README.md
README_EN.md
README_IT.md
README_JP.md
README_TW.md

- Fix link references (matching with languages)
- Use https instead of http
cc @GindaChen @Atena1118

Fix link references in READMEs

---

README.md
README_EN.md
README_TW.md

Add e-mail list in README_EN and README_TW

---

README.md
README_EN.md
README_IT.md
README_JP.md
README_TW.md

Fix e-mail list subscribe/unsubscribe and FAQ links
Ref:

Fix e-mail list subscribe/unsubscribe and FAQ links

---

README.md
README_IT.md
README_JP.md
README_TW.md

Fix INFORMATION_GUIDE link refs

---

CONTRIBUTING.md
CONTRIBUTING_EN.md
README.md
README_EN.md
README_IT.md
README_JP.md
README_TW.md

Update slack invite link again

---

README_TW.md

Optimize Traditional Chinese Language Quality

Optimize Traditional Chinese Language Quality

---

README.md

add a link to the collaborative project: Alibaba Cloud NCP free analysis platform (using partial wuhan2020 data and free).
@frank-zsy @zhuangbiaowei @Will. Wang

add a link to the collaborative project

---

README.md
README_EN.md
README_TW.md

Signed-off-by: pkufubo <pkufubo@pku.edu.cn>
使用了国家卫生健康委官方用命，避免疾病或病毒名中出现“武汉”字样，带来歧视风险。
官方通知如下：
http://www.gov.cn/zhengce/zhengceku/2020-02/22/content_5482019.htm

Use official virus names,#396

---

README_EN.md

Virus name capital form
